- name: MeleeRangeRatio
  type: float
  default: 1f
  category: Combat
  descrip: Melee attack horizontal ranges will be multiplied by this value
- name: NoConsumeFood
  type: bool
  default: true
  category: Combat
  descrip: Food won't be consumed on use
- name: PermanentThrowable
  type: bool
  default: true
  category: Combat
  descrip: Throwables won't be consumed on use
- name: NoMosaic
  type: bool
  default: true
  category: Display
  descrip: Disable dynamic mosaic
